/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RequestId = IDL.Nat;
export const TowingRequest = IDL.Record({
  'id' : RequestId,
  'vehicleType' : IDL.Text,
  'serviceDetails' : IDL.Text,
  'name' : IDL.Text,
  'dropLocation' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRequests' : IDL.Func([], [IDL.Vec(TowingRequest)], ['query']),
  'getRequest' : IDL.Func([RequestId], [IDL.Opt(TowingRequest)], ['query']),
  'submitRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RequestId = IDL.Nat;
  const TowingRequest = IDL.Record({
    'id' : RequestId,
    'vehicleType' : IDL.Text,
    'serviceDetails' : IDL.Text,
    'name' : IDL.Text,
    'dropLocation' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRequests' : IDL.Func([], [IDL.Vec(TowingRequest)], ['query']),
    'getRequest' : IDL.Func([RequestId], [IDL.Opt(TowingRequest)], ['query']),
    'submitRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };